Blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from home.views import home_screen_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from account.views import must_authenticate_view
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    # Basic urls
    path('', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('blog/', include('blogPost.urls', namespace='blogPost')),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),
    path('home/',include('home.urls'), name='api'),

    # APIs URLs
    path('api/blog/', include('blogPost.api.urls', namespace='blog_api')),
    path('api/account/', include('account.api.urls', namespace='account_api')),


    # Password reset links
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path, re_path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.registration_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('update/', views.edit_account_view, name='update'),
    path('', views.must_authenticate_view, name='must_authenticate'),

]

home/urls.py
from django.urls import path,re_path
from . import views

app_name = 'home'

urlpatterns = [
    path('api/', views.api_view, name='api'),
]

templates/snippets/bais_css.html
<style type="text/css">
    body{
		background-color: #f2f2f2;
	}
</style>

templates/snippets/footer.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/bais_style.css' %}"/>

<!-- Footer -->

<div class="d-flex flex-row align-items-center footer bg-white shadow-lg">
        <p class="mt-5 mb-3 text-muted m-auto">This is Bahaa Ibrahim Blog | &copy; 2021</p>

</div>
<!-- End Footer -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>

templates/snippets/header.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/bais_style.css' %}"/>

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <p class="h5 my-0 me-md-auto fw-normal">
    {% if request.user.is_authenticated %}
        Hello, {{ request.user.username }}
        <i class="fas fa-dragon" aria-hidden="true"></i>
    {% endif %}
  </p>

  <!-- Creat a search bar-->
  <div class="search-bar mt-sm-2 mr-2">
      <form onsubmit="return executeQuery();">
          <input class="form-control" type="text" name="q" id="id_q" placeholder="Search.... " value="{{ query }}" >
      </form>

  </div>
    <pre>    </pre>
  <nav class="my-2 my-md-0 me-md-3">
      {% if request.user.is_authenticated %}
          <a class="p-2 text-dark" href="{% url 'home'%}" style="text-decoration: none;"><i class="fas fa-home" aria-hidden="true"></i>  Home</a>
          <a class="p-2 text-dark" href="{% url 'home:api'  %}" style="text-decoration: none;"><i class="fas fa-ankh"></i>  API</a>
        <a class="p-2 text-dark" href="{% url 'account:update' %}" style="text-decoration: none;"><i class="fas fa-user-ninja" aria-hidden="true"></i>   Account</a>
        <a class="p-2 text-dark" href="{% url 'account:logout' %}" style="text-decoration: none;"><i class="fas fa-power-off" aria-hidden="true"></i>  Logout</a>
      {% else %}
          <a class="p-2 text-dark" href="{% url 'home'%}" style="text-decoration: none;"> <i class="fas fa-home" aria-hidden="true"></i>  Home</a>
          <a class="p-2 text-dark" href="{% url 'home:api'  %}" style="text-decoration: none;"><i class="fas fa-ankh"></i>  API</a>
          <a class="p-2 text-dark" href="{% url 'account:login' %}" style="text-decoration: none;"><i class="fas fa-unlock-alt" aria-hidden="true"></i>  Login</a>
          <a class="btn btn-outline-primary" href="{% url 'account:register' %}" style="text-decoration: none;"><i class="fas fa-user-plus" aria-hidden="true"></i>  Register</a>
      {% endif %}
  </nav>
</div>

<script type="text/javascript">
	document.getElementById("id_q").value = "{{query}}"
</script>

<script>
function executeQuery() {
    var query = document.getElementById('id_q').value;
    window.location.replace("http://127.0.0.1:8000/?q=" + query)
    //"https://open-api.xyz/?q=" + query;  (if we are in production ENV)
    return false
}

</script>