Blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from home.views import home_screen_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from account.views import must_authenticate_view
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    # Basic urls
    path('', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('blog/', include('blogPost.urls', namespace='blogPost')),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),
    path('home/',include('home.urls'), name='api'),

    # APIs URLs
    path('api/blog/', include('blogPost.api.urls', namespace='blog_api')),
    path('api/account/', include('account.api.urls', namespace='account_api')),


    # Password reset links
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogPost/api/urls.py
from django.urls import path
from .views import api_detail_view, api_update_view, api_delete_view, api_create_view, api_is_author_of_blogpost, ApiClassBasedView

app_name = 'blog'

urlpatterns = [
    path('<slug>/',api_detail_view, name='detail'),
    path('<slug>/update',api_update_view, name='update'),
    path('<slug>/delete', api_delete_view, name='delete'),
    path('create', api_create_view, name='create'),
    path('list', ApiClassBasedView.as_view(), name='list'),
    path('<slug>/is_author', api_is_author_of_blogpost, name="is_author"),

]

blogPost/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blogpost'
urlpatterns = [
    path('create/', views.create_blog_view, name='create'),
    path('<slug>/', views.detail_blog_view, name='detail'),
    path('<slug>/update', views.update_blog_view, name='update'),
    path('<slug>/delete/', views.delete_blog_view, name='delete'),
    path('<slug>/favorite/', views.favorite_view, name='favorite'),

]

blogPost/models.py
from django.db import models
from django.db.models.signals import post_delete, pre_save
from django.utils.text import slugify
from django.conf import settings
from django.dispatch import receiver

# Create your models here.


# determine the save location for images
def upload_location(instance, filename, **kwargs):
    file_path = 'blog/{author_id}/{title}-{filename}'.format(
        author_id=str(instance.author.id),
        title=str(instance.title),
        filename=filename
    )
    return file_path


class BlogPost(models.Model):
    title = models.CharField(max_length=50, null=False, blank=True)
    body = models.TextField(max_length=5000, null=False, blank=True)
    image = models.ImageField(upload_to=upload_location, null=False, blank=True)
    date_published = models.DateTimeField(auto_now_add=True, verbose_name='Published Date')
    date_updated = models.DateTimeField(auto_now=True, verbose_name='Updated Date')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, unique=True)
    isFavorite = models.BooleanField(default=False)

    def __str__(self):
        return self.title


@receiver(post_delete, sender=BlogPost)
# to make sure that the image is deleted when the post deleted
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)


# called before the post saved or committed to the DB (for pre save)
def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username+'-'+instance.title)


pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

blogPost/forms.py
from django import forms
from .models import BlogPost


class CreateBlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']


class UpdateBlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']

        def save(self, commit=True):
            blog_post = self.inistance
            blog_post.title = self.cleaned_data['title']
            blog_post.body = self.cleaned_data['body']
            if self.cleaned_data['image']:
                blog_post.image = self.cleaned_data['image']
            if commit:
                blog_post.save()
            return blog_post

blogPost/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from .serializers import BlogSerializer, BlogPostUpdateSerializer, BlogPostCreateSerializer
from blogPost.models import BlogPost
from rest_framework.pagination import PageNumberPagination
from rest_framework.generics import ListAPIView
from rest_framework.authentication import TokenAuthentication
from account.models import Account
# imports for Restricting access with permissions.
from rest_framework.permissions import IsAuthenticated
from rest_framework.filters import SearchFilter, OrderingFilter


# Create view for GET request of the API using Function based views
@api_view(['GET', ])
@permission_classes((IsAuthenticated, ))
def api_detail_view(request, slug):
    try:
        post = BlogPost.objects.get(slug=slug)
    except BlogPost.DoesNotExist:
        return Response({'response': "This post doesn't exist or deleted"}, status=status.HTTP_404_NOT_FOUND)
    if request.method == 'GET':
        serializer = BlogSerializer(post)
        return Response(serializer.data)


# a view of PUT request 'Update , edit' of the API
@api_view(['PUT', ])
# for make sure that only the author of the post is the same author with the token.
@permission_classes((IsAuthenticated, ))
def api_update_view(request, slug):
    try:
        blog_post = BlogPost.objects.get(slug=slug)
    except BlogPost.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    user = request.user
    if blog_post.author != user:
        return Response({'response': "You don't have permission to edit that."})

    if request.method == 'PUT':
        serializer = BlogPostUpdateSerializer(blog_post, data=request.data, partial=True)
        data = {}
        if serializer.is_valid():
            serializer.save()
            data['response'] = "Update Successful"
            data['pk'] = blog_post.pk
            data['title'] = blog_post.title
            data['body'] = blog_post.body
            data['slug'] = blog_post.slug
            data['date_updated'] = blog_post.date_updated
            image_url = str(request.build_absolute_uri(blog_post.image.url))
            if "?" in image_url:
                image_url = image_url[:image_url.rfind("?")]
            data['image'] = image_url
            data['username'] = blog_post.author.username
            return Response(data=data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# a view of DELETE request of the API
@api_view(['DELETE', ])
@permission_classes((IsAuthenticated, ))
def api_delete_view(request, slug):
    try:
        post = BlogPost.objects.get(slug=slug)
    except BlogPost.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    user = request.user
    if post.author != user:
        return Response({'response': "You don't have permission to delete this."})
    if request.method == 'DELETE':
        operation = post.delete()
        data = {}
        if operation:
            data['success'] = 'Delete Successful'
        else:
            data['fail'] = 'Delete Failed'
        return Response(data=data)


# a view of POST request of API for create a new Blog post
@api_view(['POST', ])
@permission_classes((IsAuthenticated, ))
def api_create_view(request):
    if request.method == 'POST':
        data = request.data
        data['author'] = request.user.pk
        serializer = BlogPostCreateSerializer(data=data)

        data = {}
        if serializer.is_valid():
            blog_post = serializer.save()
            data['response'] = "created"
            data['pk'] = blog_post.pk
            data['title'] = blog_post.title
            data['body'] = blog_post.body
            data['slug'] = blog_post.slug
            data['date_updated'] = blog_post.date_updated
            image_url = str(request.build_absolute_uri(blog_post.image.url))
            if "?" in image_url:
                image_url = image_url[:image_url.rfind("?")]
            data['image'] = image_url
            data['username'] = blog_post.author.username
            return Response(data=data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET',])
@permission_classes((IsAuthenticated,))
def api_is_author_of_blogpost(request, slug):
    try:
        blog_post = BlogPost.objects.get(slug=slug)
    except BlogPost.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    data = {}
    user = request.user
    if blog_post.author != user:
        data['response'] = "You don't have permission to edit that."
        return Response(data=data)
    data['response'] = "You have permission to edit that."
    return Response(data=data)



# define class for pagination (divide posts list into pages)  also use class based views
class ApiClassBasedView(ListAPIView):
    # Query all blogs into a list (create queryset)
    queryset = BlogPost.objects.all()
    serializer_class = BlogSerializer
    authentication_classes = (TokenAuthentication, )
    permission_classes = (IsAuthenticated, )
    pagination_class = PageNumberPagination

    # for Search & filtering &ordering
    filter_backends = (SearchFilter, OrderingFilter)
    search_fields = ('title', 'body', 'author__username')
    '''
    author__username' we want to search in a specific attribute in the author (author's username) 
    if there's a FK we use (model__particular field with in the model which is the author because it's the FK).
    '''

blogPost/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.db.models import Q
from django.http import JsonResponse
from .models import BlogPost
from account.models import Account
from .forms import CreateBlogPostForm, UpdateBlogPostForm


# Create your views here.
def create_blog_view(request):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        post.author = author
        post.save()
        form = CreateBlogPostForm()

    context['create_blog_form'] = form

    return render(request, 'blogPost/create_blog.html', context)


def detail_blog_view(request, slug):
    context = {}
    blog_post = get_object_or_404(BlogPost, slug=slug)
    context['blog_post'] = blog_post
    return render(request, 'blogPost/detail_blog.html', context)


def update_blog_view(request, slug):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    blog_post = get_object_or_404(BlogPost, slug=slug)
    if blog_post.author != user:
        return HttpResponse("You aren't the owner of this post.")

    if request.POST:
        form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = 'Updated'
            blog_post =obj
    form = UpdateBlogPostForm(
        initial = {
            'title' : blog_post.title,
            'body' : blog_post.body,
            'image' : blog_post.image,
        }
    )
    context['form'] = form
    return render(request, 'blogPost/update_blog.html', context)


# View for delete post
def delete_blog_view(request, slug):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
    blog_post = get_object_or_404(BlogPost, slug=slug)
    if blog_post.author != user:
        return HttpResponse("You aren't the owner of this post.")

    operation = blog_post.delete()
    if operation:
        return redirect("home")
    return render(request, 'home/home.html', context)


# view for set a favorite posts
def favorite_view(request, slug):
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
    post = get_object_or_404(BlogPost, slug=slug)
    try:
        if post.isFavorite:
            post.isFavorite = False
        else:
            post.isFavorite = True
        post.save()
    except (KeyError, BlogPost.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return redirect("home")


# define a search function
def get_blog_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        posts = BlogPost.objects.filter(
            Q(title__icontains=q),
            Q(body__icontains=q)
        ).distinct()

        for post in posts:
            queryset.append(post)
    return list(set(queryset))

blogPost/templates/blogPost/create_blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'blogPost/styles/blog_post_style.css' %}"/>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required></textarea>
				</div>

				<!-- Image -->
				<div class="form-group">
					<label for="id_image">Image</label>
					<input  type="file" name="image" id="id_image" accept="image/*" required>

				</div>

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit"><i class="fas fa-cloud-upload-alt" aria-hidden="true"></i>   POST</button>
			</form>
		</div>
	</div>
</div>

{% endblock content %}

blogPost/templates/blogPost/detail_blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <link rel="stylesheet" type="text/css" href="{% static 'blogPost/styles/blog_post_style.css' %}"/>


<div class="container">
	<div class="row">

		<!-- Blog post -->
		<div class="card m-auto">
			<img class="card-img-top" src="{{blog_post.image.url}}">
			<div class="card-body my-2">
				<h2 class="card-title">{{blog_post.title}}</h2>
                {% autoescape off %}
				        <p class="card-text">{{blog_post.body|linebreaksbr}}</p>
                {% endautoescape %}
                <p>
					{% if blog_post.author == request.user %}
						<a href="{% url 'blogpost:update' blog_post.slug %}" class="btn btn-primary">Update</a>
					{% endif %}
				</p>
			</div>
			<div class="card-footer text-muted">
				Updated on {{blog_post.date_updated}} by {{blog_post.author}}
			</div>
		</div>
		<!-- end Blog post -->

	</div>
</div>

{% endblock content %}

blogPost/templates/blogPost/update_blog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <link rel="stylesheet" type="text/css" href="{% static 'blogPost/styles/blog_post_style.css' %}"/>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..."
					required>{{form.initial.body}}</textarea>
				</div>

				<!-- Image -->
				<div class="form-group image-group" id="id_image_group">
					<img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
					  <div class="middle">
					    <div class="text">Change image</div>
					  </div>
				</div>
				<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">


				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };
	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}